/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_uart_blue_GpioControl */

#ifndef _Included_com_example_uart_blue_GpioControl
#define _Included_com_example_uart_blue_GpioControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_uart_blue_GpioControl
 * Method:    readGpioValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_uart_1blue_GpioControl_readGpioValue
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
